### ISSUE TITLE
The raycasted depth map does not match the raw depth map

### ISSUE THREAD

**Issue by CanCanZeng** [GerhardR/kfusion#8]
Hi, thank you for sharing this code, it's very helpful for a starter in 3D reconstruction like me. But I found that the raycasted depth map does not match the raw depth map, I use opencv to get the raycasted depth map, the code is something like this:

cv::Mat vertex_raycasted(480, 640, CV_32FC3);
cudaMemcpy(vertex_raycasted.data, kfusion.vertex.data(), 480*640*sizeof(float)*3, cudaMemcpyDeviceToHost);
vector<cv::Mat> channels_of_vertex;
cv::split(vertex_raycasted, channels_of_vertex);
cv::Mat xmap = (channels_of_vertex[0] - 0.4) * 1000;
cv::Mat ymap = (channels_of_vertex[1] - 0.4) * 1000;
cv::Mat depthmap_raycasted = channels_of_vertex[2];
depthmap_raycasted *= 1000;

and compare it with original depth image or the raw depth map in kfusion, using this code:

cv::Mat vertex_input(480, 640, CV_32FC3);
cudaMemcpy(vertex_input.data, kfusion.inputVertex[0].data(), 480*640*sizeof(float)*3, cudaMemcpyDeviceToHost);
vector<cv::Mat> channels_of_vertex2;
cv::split(vertex_input, channels_of_vertex2);
xmap = (channels_of_vertex2[0] - 0.4) * 1000;
ymap = (channels_of_vertex2[1] - 0.4) * 1000;
cv::Mat depthmap_input = channels_of_vertex2[2];
depthmap_input *= 1000;

the original depth image is very similar to raw depth map, since only bilateral filter is applied, this is common. But it is strange that the raycasted depth map is different from the original depth image and raw depth map, thought they looks very similar. I transformed them into point cloud in matlab, there is a big translation and rotation between them, and the translation and rotation is changing with time. I mounted the camera on a robot arm, and found that the pose computed by TSDF is rather accurate, only few millimeter's error. It confused me for a long time, can you help me?

![rawdepthmap](https://user-images.githubusercontent.com/26817559/39474173-37ac1112-4d85-11e8-8b2c-eefa913d9c90.png)

![raycasted](https://user-images.githubusercontent.com/26817559/39474169-323cf4da-4d85-11e8-9e99-947e9b115150.png)

the first image is raw depth map, and second is raycasted depth map, they look alike, but the depth values are very different.

**Comment by GerhardR** [comment]
Hi,

the kfusion.vertex image does not store coordinates in the local camera
frame, but the 3D coordinates in world frame. So it doesn't make sense to
just use the 3rd coordinate as a depth value.

cheers,
  Gerhard

**Comment by CanCanZeng** [comment]
@GerhardR Thanks for your reply, I will take a closer look at the code.

**Comment by CanCanZeng** [comment]
@GerhardR Your answer is a good solution to my problem, thank you again.
